variables: 
- group: Harbor_Creds
- group: githubtoken
- group: githubemail

trigger:
- main

resources: 
  - repo: self

stages:
- stage:
  displayName: Build_and_push_image 
  jobs:  
  - job: Build_and_Push
    steps:
      - bash: |
          # Building Docker Image
          docker build -t $(imagename) .
          # Logging into Registry
           docker login --username $(username) --password $(password) $(registry)
          # Tagging Image
          docker tag $(imagename) $(registry)/$(repository):$(Build.BuildId)
          # Pushing Image to Registry
          docker push $(registry)/$(repository):$(Build.BuildId)

      - bash: |
          condition: not(contains(variables['Build.SourceVersionMessage'], '[skip ci]'))
          # installing yq to update kustomization.yaml
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq
          yq --version
          cd k8smanifests
          yq -i '.images[0].newTag = "'$(Build.BuildId)'"' -i kustomization.yaml
          cd ..
          git config --global user.name "$(github_name)"
          git config --global user.email "$(github_email)"
          git fetch 
          git checkout main
          git add .
          git commit -m "[skip ci]"
          git push -o ci.skip https://franclin1:$GIT_PUSH_TOKEN@github.com/franclin1/pacmangithub
     


   