variables: 
- group: Harbor_Creds

trigger:
- main

resources: 
  - repo: self

stages:
- stage:
  displayName: Build Image 
  jobs:  
  - job: Build
    steps:
      - bash: |
          # Building Docker Image
          echo $(repository)
          docker build -t $(imagename) .
          # Logging into Registry
           docker login --username $(username) --password $(password) $(registry)
          # Tagging Image
          docker tag $(imagename) $(registry)/$(repository)
          # Pushing Image to Registry
          docker push $(registry)/$(repository)
    step:
      - task: KubernetesManifest@0
        displayName: Deploy
        inputs:
          kubernetesServiceConnection: k8s
          namespace: malteahlers
          manifests: |
            manifests/pacman.yaml
            mongodb.yaml
         

        