variables: 
- group: Harbor_Creds
- name: username
  value: $[variables.username]
- name: password
  value: $[variables.password]
- name: registry
  value: $[variables.registry]
- name: imageRepository
  value: $[variables.repository]
  vmImageName: "ubuntu-latest"
  containerRegistry: "harbor_registry"
  dockerfilePath: "**/Dockerfile"
  tag: '$(Build.BuildId)'

trigger:
- main

resources: 
  - repo: self

stages:
- stage:
  displayName: Build Image 
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)
    steps:
      - bash: |
          # Building Docker Image
          docker build -t test .
          # Logging into Registry
           docker login --username $(username) --password $(password) $(registry)
          # Tagging Image
          docker tag test harbor.skyered-devops.de/pacman/test
          # Pushing Image to Registry
          docker push harbor.skyered-devops.de/pacman/test


   