variables: 
- group: Harbor_Creds

trigger:
- main

resources: 
  - repo: self

stages:
- stage:
  displayName: Build Image 
  jobs:  
  - job: Build
    steps:
      - bash: |
          # Building Docker Image
          echo $(repository)
          docker build -t $(imagename) .
          # Logging into Registry
           docker login --username $(username) --password $(password) $(registry)
          # Tagging Image
          docker tag $(imagename) $(registry)/$(repository)
          # Pushing Image to Registry
          docker push $(registry)/$(repository)

      - task: KubernetesManifest@0
        displayName: Deploy to the new namespace in the Kubernetes cluster
        inputs:
          kubernetesServiceConnection: k8s 
          action: deploy
          manifests: |
              pacman.yaml

   