variables: 
- group: Harbor_Creds

trigger:
- main

resources: 
  - repo: self

stages:
- stage:
  displayName: Build_and_push_image 
  jobs:  
  - job: Build_and_Push
    steps:
      - bash: |
          # Building Docker Image
          echo $(repository)
          echo $(Build.BuildId)
          docker build -t $(imagename) .
          # Logging into Registry
           docker login --username $(username) --password $(password) $(registry)
          # Tagging Image
          docker tag $(imagename) $(registry)/$(repository):$(Build.BuildId)
          # Pushing Image to Registry
          docker push $(registry)/$(repository):$(Build.BuildId)

      - bash: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq
          yq --version
          cd k8smanifests
          yq e '.images[0].newTag = "'$GITHUB_SHA'"' -i kustomization.yaml
          git config --global user.name "${GITLAB_USER_NAME}"
          git config --global user.email "${GITLAB_USER_EMAIL}"
          git checkout main
          git add .
          git commit -m "updated_image"
          git push -o ci.skip https://franclin1:$GIT_PUSH_TOKEN@github.com/franclin1/pacmangithub
     


   