variables: 
- group: Harbor_Creds



trigger:
- main

resources: 
  - repo: self

stages:
- stage:
  displayName: Build Image 
  jobs:  
  - job: Build
    steps:
      - bash: |
          # Building Docker Image
          echo $(repository)
          docker build -t test .
          # Logging into Registry
           docker login --username $(username) --password $(password) $(registry)
          # Tagging Image
          docker tag test harbor.skyered-devops.de/pacman/test
          # Pushing Image to Registry
          docker push harbor.skyered-devops.de/pacman/test


   