variables: 
  crHostname: ""
  crName: "pacman"
  imageRepository: "application1"
  vmImageName: "ubuntu-latest"
  imageName: "pacman_application"
  tag: "latest"
  dockerfilePath: "**/Dockerfile"

trigger:
- main

stages:
- stage:
  displayName: Build Image
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build an Docker Image
      inputs:
        containerRegistry: '$(crHostname)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
