variables: 
- group: Harbor_Creds

trigger:
- main

resources: 
  - repo: self

stages:
- stage:
  displayName: Build_and_push_image 
  jobs:  
  - job: Build and Push
    steps:
      - bash: |
          # Building Docker Image
          echo $(repository)
          docker build -t $(imagename) .
          # Logging into Registry
           docker login --username $(username) --password $(password) $(registry)
          # Tagging Image
          docker tag $(imagename) $(registry)/$(repository)
          # Pushing Image to Registry
          docker push $(registry)/$(repository)

      - bash: |
          wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/local/bin/yq
          yq --version
          yq e '.images[0].newTag = "MOIN"' -i kustomization.yaml

     


   