apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mongodb-pvc
  namespace: malteahlers
  labels: 
    app: mongodb
spec:
  accessModes: 
    - ReadWriteOnce
  volumeName: mongodb-pvc
  resources: 
    requests: 
      storage: 1Gi
  